### PR TITLE
feature/multiple configs

### PR DESCRIPTION
**Pull request by baywet**
- **feat: split reacts rules to avoid impacting non-react projects**
- **4.1.0**

### CODE REVIEW

**Comment by baywet** [comment]
depends on #12 to be merged in first

**Comment by baywet** [comment]
context https://archive.eslint.org/docs/developer-guide/shareable-configs#sharing-multiple-configs

**Review by MIchaelMainer — DISMISSED** [review]

**Comment by gavinbarron** [comment]
@baywet TYVM for this. Could you please also update the read me with an example of how to use the core rules only?

**Comment by baywet** [comment]
> @baywet TYVM for this. Could you please also update the read me with an example of how to use the core rules only?

done!

**Review by MIchaelMainer — APPROVED** [review]

**Pull request merged**
